### ISSUE TITLE
Unable to correctly sort images with ID going beyond 9999

### ISSUE THREAD

**Issue by leon-gan** [jonpecar/qrCodeImageSorterGUI#13]
The sorter is unable to sort images into a specified folder when the list of images being sorted contains filenames/IDs IMG_9999 and IMG_0001. This issue is known to occur with photos taken on an iPhone where they are assigned names from IMG_0001 to IMG_9999. After having taken an IMG_9999, the iPhone camera/photos app will then cycle/loop back to IMG_0001 when the next photo is taken.

For example, if I had 4 images (IMG_9998, IMG_9999, IMG_0001, IMG_0002) and I intended to have them sorted into one folder, IMG_9998 and IMG_9999 will be the included in the specified folder and any other images from IMG_0001 and IMG_0002 will automatically be allocated into a new folder.

If it's possible, instead of having the images sorted based on the image filename/ID, maybe using timestamps of the photos could prevent this issue.

**Comment by jonpecar** [comment]
There is now an option available in the GUI to use the dates on images instead of the name for the order.
